name: Deploy to ECR
# deploy
on: 
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and Push Images
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, test, tag, and push application image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: webapp-assignment1
        APPLICATION_IMAGE_TAG: mywebapp
      run: |
        # Docker build and push application image 
        cd flaskapp/
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:application-$APPLICATION_IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:application-$APPLICATION_IMAGE_TAG

    - name: Build, test, tag, and push MySQL image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: mysql-assignment1
        MYSQL_IMAGE_TAG: mysql
      run: |
        # Docker build and push MySQL image
        cd flaskapp/
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:mysql-$MYSQL_IMAGE_TAG -f Dockerfile_mysql .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:mysql-$MYSQL_IMAGE_TAG

    - name: Add SSH private key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Configure EC2 instance and install Docker
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        AWS_REGION: us-east-1
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      run: |
        # Start the SSH agent and add the SSH private key
        echo "${{ secrets.EC2_SSH_KEY }}" | ssh-agent bash -c 'ssh-add /dev/stdin; ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << EOF
          sudo yum update -y
          sudo yum install -y docker
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -aG docker ec2-user
        EOF'

    - name: Pull Docker images from Amazon ECR and run containers
      env:
        AWS_REGION: us-east-1
      run: |
        # Log in to ECR and pull the Docker images
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}
        docker pull $ECR_REGISTRY/webapp-assignment1:application-mywebapp
        docker pull $ECR_REGISTRY/mysql-assignment1:mysql-mysql

        # Run MySQL container
        docker run -d --name sql_container --network assignment-network -e MYSQL_ROOT_PASSWORD=db_pass123 -p 3306:3306 990835861266.dkr.ecr.us-east-1.amazonaws.com/mysql-assignment1:sql_image

        docker run -d --name blue-container --network assignment-network -e DBHOST=mysql-db -e DBPORT=3306 -e DBUSER=root -e DBPWD=db_pass123 -e DATABASE=mydb -e APP_COLOR=blue -p 8081:8080 990835861266.dkr.ecr.us-east-1.amazonaws.com/webapp-assignment1:webapp_images

        docker run -d --name pink-container --network assignment-network -e DBHOST=mysql-db -e DBPORT=3306 -e DBUSER=root -e DBPWD=db_pass123 -e DATABASE=mydb -e APP_COLOR=pink -p 8082:8080 990835861266.dkr.ecr.us-east-1.amazonaws.com/webapp-assignment1:webapp_images

        docker run -d --name lime-container --network assignment-network -e DBHOST=mysql-db -e DBPORT=3306 -e DBUSER=root -e DBPWD=db_pass123 -e DATABASE=mydb -e APP_COLOR=lime -p 8083:8080 990835861266.dkr.ecr.us-east-1.amazonaws.com/webapp-assignment1:webapp_images
