name: Deploy to ECR

on: 
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and Push Images
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, test, tag, and push application image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: webapp-assignment1
        APPLICATION_IMAGE_TAG: mywebapp
      run: |
        cd flaskapp/
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$APPLICATION_IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$APPLICATION_IMAGE_TAG

    - name: Build, test, tag, and push MySQL image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: mysql-assignment1
        MYSQL_IMAGE_TAG: mysql
      run: |
        cd flaskapp/
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$MYSQL_IMAGE_TAG -f Dockerfile_mysql .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$MYSQL_IMAGE_TAG

    - name: Set up SSH key for EC2
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/key.pem
        chmod 600 ~/.ssh/key.pem

    - name: SSH into EC2 and configure Docker
      run: |
        ssh -t -o StrictHostKeyChecking=no -i ~/.ssh/key.pem ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          sudo yum update -y
          sudo yum install -y docker
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -aG docker ec2-user
          # Ensure the Docker image is pulled from the correct ECR registry
          sudo docker pull $ECR_REGISTRY/webapp-assignment1:mywebapp
          sudo docker pull $ECR_REGISTRY/mysql-assignment1:mysql
          sudo docker run -d --name your-container-name $ECR_REGISTRY/webapp-assignment1:mywebapp
        EOF

    - name: Pull Docker images from Amazon ECR and run containers
      env:
        AWS_REGION: us-east-1
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        # Log in to ECR and pull the Docker images
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
        docker pull $ECR_REGISTRY/webapp-assignment1:mywebapp
        docker pull $ECR_REGISTRY/mysql-assignment1:mysql

        docker network create assignment-network

        # Run MySQL container
        docker run -d --name sql_container --network assignment-network -e MYSQL_ROOT_PASSWORD=db_pass123 -e MYSQL_DATABASE=mydb -p 3306:3306 $ECR_REGISTRY/mysql-assignment1:mysql

        docker run -d --name blue-container --network assignment-network -e DBHOST=mysql-db -e DBPORT=3306 -e DBUSER=root -e DBPWD=db_pass123 -e DATABASE=mydb -e APP_COLOR=blue -p 8081:8080 $ECR_REGISTRY/webapp-assignment1:mywebapp

        docker run -d --name pink-container --network assignment-network -e DBHOST=mysql-db -e DBPORT=3306 -e DBUSER=root -e DBPWD=db_pass123 -e DATABASE=mydb -e APP_COLOR=pink -p 8082:8080 $ECR_REGISTRY/webapp-assignment1:mywebapp

        docker run -d --name lime-container --network assignment-network -e DBHOST=mysql-db -e DBPORT=3306 -e DBUSER=root -e DBPWD=db_pass123 -e DATABASE=mydb -e APP_COLOR=lime -p 8083:8080 $ECR_REGISTRY/webapp-assignment1:mywebapp

        docker ps
        docker ps -a